apiVersion: v1
kind: Pod
metadata:
  name: crictl-cleaner
spec:
  nodeName: k8s-node-1
  hostPID: true
  containers:
    - name: crictl
      image: alpine
      command: ["/bin/sh", "-c", "chroot /host crictl rmi k8s-node-1.local:5000/micewriter-engine:latest || true"]
      securityContext:
        privileged: true
      volumeMounts:
        - name: host
          mountPath: /host
  volumes:
    - name: host
      hostPath:
        path: /
  restartPolicy: Never
